CREATE TABLE IF NOT EXISTS transaction (
  ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data VARCHAR(1000) NOT NULL,
  amount number(26, 6),
  reference varchar(1000),
  created_at TIMESTAMP NOT NULL default NOW()
);